spring:
  application:
    name: Board Service

  profiles:
    active: local # default로 사용될 프로파일 명시
    include: redis, mail-account, slack # 분리되어 있는 application-redis.yml를 포함

  datasource:
    url: jdbc:h2:mem:board
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

#  data:
#    redis:
#      host: 127.0.0.1
#      port: 6379
#      password:

jwt:
  secret.access-token: 2z6oNf/GwepEYumNk5rJSIyADL+WQ3YrArbVv+LTQJs=
  secret.refresh-token: iRQMvddwE87VpLcGhbrt7QEfR9tN7x84Zkr+0ifOALM=
  expiration-seconds.access-token: 3600 # 1시간
  expiration-seconds.refresh-token: 2592000 # 30일
  # expiration-seconds.access-token: 30 # 테스트용 30초
  # expiration-seconds.refresh-token: 30 # 테스트용 30초

--- # 프로파일을 구분

spring:
  config:
    activate:
      on-profile: local # 해당 프로파일이 선택되었을 때만 활성화

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

---

spring:
  config:
    activate:
      on-profile: test


  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never
