
### 게시글 등록
POST {{domain}}/api/v1/articles
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title" : "게시글 제목입니다.",
  "content" : "게시글 내용입니다."
}

### 게시글 1건 조회
GET {{domain}}/api/v1/articles/1
Authorization: Bearer {{accessToken}}

### 게시글 리스트 조회
GET {{domain}}/api/v1/articles
Authorization: Bearer {{accessToken}}

### 게시글 리스트 조회
GET {{domain}}/api/v1/articles?pageNumber=1&pageSize=1&direction=asc&property=id
Authorization: Bearer {{accessToken}}

### 게시글 수정
PUT {{domain}}/api/v1/articles/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title" : "게시글 제목",
  "content" : "게시글 내용"
}

### 게시글 삭제
DELETE {{domain}}/api/v1/articles/1
Authorization: Bearer {{accessToken}}
